name: CI/CD Maple ERP Backend

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    env:
      # Definindo variáveis de ambiente para testes
      # Valores reais são armazenados nos secrets do GitHub
      NODE_ENV: test
      # Usamos variáveis de ambiente de teste para CI
      DATABASE_URL: ${{ secrets.TEST_DATABASE_URL || 'postgresql://test:test@localhost:5432/test_db' }}
      CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME || 'test_cloud' }}
      CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY || 'test_key' }}
      CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET || 'test_secret' }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Atualizando para Node.js 18 LTS
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint
        
      # Quando os testes forem implementados, descomente esta seção
      # - name: Run tests
      #   run: npm test
      
      - name: Check build
        run: npm run build --if-present
        
  # Adicione este job quando estiver pronto para deploy automático
  # deploy:
  #   needs: build-and-test
  #   if: github.ref == 'refs/heads/main' && github.event_name == 'push'
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Deploy to production
  #       run: echo "Implementar deploy para produção aqui"

